apiVersion: v1
kind: Secret
metadata:
  name: kite-secrets
  namespace: kite
  labels:
    app: kite
type: Opaque
stringData:
  database-username: "kite"
  database-password: "changeme"
  jwt-secret: "change-this-secret-in-production-min-32-chars"
  redis-password: ""
