apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kite.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kite.labels" . | nindent 4 }}
data:
  DATABASE_HOST: {{ .Values.database.host | quote }}
  DATABASE_PORT: {{ .Values.database.port | quote }}
  DATABASE_NAME: {{ .Values.database.name | quote }}
  DATABASE_USERNAME: {{ .Values.database.username | quote }}
  REDIS_HOST: {{ .Values.redis.host | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
  QUEUE_NATS_URL: {{ .Values.queue.natsUrl | quote }}
